development:
  adapter: postgresql
  encoding: unicode
  database: airbnb_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: airbnb_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: airbnb_production
  pool: 5
